const headers = [
  'id',
  'singular',
  'adjective',
  'plural',
  'possessive',
  'startWithVowel',
  'unknown',
  'pronoun',
  'article',
  'description',
  'name',
  'icon',
  'levelItem',
  'rarity',
  'filterGroup',
  'additionalData',
  'itemUICategory',
  'itemSearchCategory',
  'equipSlotCategory',
  'itemSortCategory',
  'unknown2',
  'startSize',
  'isUnique',
  'isUntradable',
  'isIndisposable',
  'lot',
  'priceMid',
  'priceLow',
  'canHQ',
  'dyeCount',
  'isCrestWorthy',
  'itemAction',
  'castTime',
  'cooldown',
  'classJobRepair',
  'itemRepair',
  'itemGlamour',
  'desynth',
  'collectable',
  'alwaysCollectable',
  'aetherialReduce',
  'levelEquip',
  'requiredPVPRank',
  'equipRestriction',
  'classJobCategory',
  'grandCompany',
  'itemSeries',
  'baseParamModifier',
  'modelMain',
  'modelSub',
  'classJobUse',
  'unknown3',
  'damagePhysical',
  'damageMagical',
  'delay',
  'unknown4',
  'blockRate',
  'block',
  'defensePhysical',
  'defenseMagical', 
  'baseParam0', 
  'baseParamValue0',
  'baseParam1', 
  'baseParamValue1',
  'baseParam2', 
  'baseParamValue2',
  'baseParam3', 
  'baseParamValue3',
  'baseParam4', 
  'baseParamValue4',
  'baseParam5', 
  'baseParamValue5',
  'itemSpecialBonus',
  'itemSpecialBonusParam',
  'baseParamSpecial0',
  'baseParamValueSpecial0',
  'baseParamSpecial1',
  'baseParamValueSpecial1',
  'baseParamSpecial2',
  'baseParamValueSpecial2',
  'baseParamSpecial3',
  'baseParamValueSpecial3',
  'baseParamSpecial4',
  'baseParamValueSpecial4',
  'baseParamSpecial5',
  'baseParamValueSpecial5',
  'materializeType',
  'materiaSlotCount',
  'isAdvancedMeldingPermitted',
  'isPVP',
  'subStatCategory',
  'isGlamourous',
];

const rows = (data) => {
  let i = 0;

  while (data[i][0] !== '0') {
    i++;
  }

  return data.slice(i);
};

export default {
  tableName: 'item',
  type: 'csv',
  delimiter: ',',
  file: '../datamining/csv/Items.csv',
  headers,
  rows
};
